name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Build and deploy Jekyll site
      uses: helaili/jekyll-action@2.0.1
      if: github.ref == 'refs/heads/main'
      with:
        jekyll_src: ./docs/source
