name: "Sphinx: Render docs"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your actual requirements file if you have one

      - name: Set up environment variables
        run: |
          echo "GA_ACCOUNT_NUMBER=${{ secrets.GA_ACCOUNT_NUMBER }}" >> $GITHUB_ENV

      - name: Build HTML
        run: sphinx-build -b html docs docs/build/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html-docs
          path: docs/build/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML artifacts
        uses: actions/download-artifact@v2
        with:
          name: html-docs
          path: docs/build/html/

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your actual requirements file if you have one

      - name: Set up environment variables
        run: |
          echo "GA_ACCOUNT_NUMBER=${{ secrets.GA_ACCOUNT_NUMBER }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
